# mod
mod_id=optifinecitpatch
mod_name=OptiFine CIT Patch Meow
mod_version=1.0.4.1
mod_author=["Nischhelm"]
mod_description=Patches Enchantment Ids not being found in CITs being used as 'any' enchantment breaking the CITs
mod_url=https://github.com/RuiXuqi/OptifineCITPatchMeow
mixin_loader_class=optifinecitpatch.OptiFineCITPatchPluginEarly

# gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.installations.auto-download=false

# minecraft
minecraft_version=1.12.2

# forge
forge_gradle_version=6.0.+
forge_version=14.23.5.2860
mappings_channel=stable
mappings_version=39-1.12

# mixin
mixin_gradle_version=0.7.+
mixin_version=0.8.7